spring.datasource.url=${jdbc:postgresql://dpg-d132ocruibrs73foms20-a/deploy_backend_jldj}
spring.datasource.username=${deploy_backend_jldj_user}
spring.datasource.password=${I21MqXQKxxIF8p62splHC0vvhK6v7Uav}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
