spring.datasource.url=jdbc:postgresql://dpg-d0vrf87diees73f5l6lg-a.oregon-postgres.render.com/prova_80bj
spring.datasource.username=prova_80bj_user
spring.datasource.password=WDR4YCIiWHAbG5YSbMYISJUwjhSwh1ii

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
